application:
  port: 3000
here:
  app: 8wXkwyaiOQ88gVFY0SAL
  secret: zzSC8__n856WUf7mDyeeKQ
knex:
  client: "pg"
  debug: false
  connection:
    host: "localhost"
    port: 5432
    user: "govhack"
    password: "govhack"
    database: "govhack"
danger-area:
  scale-factor: 1.5
  impact-threshold: 20
factor-impact-defaults:
  criminal_incident: 5
